version: "3"

tasks:
  generate_go_by_protobufs:
    aliases:
      - gen_go
    desc: "Generate go files for protobufs"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
